### ISSUE TITLE
horizontal chart

### ISSUE THREAD

**Issue by umazalakain** [wesnolte/jOrgChart#30]
Doing it with CSS alone it's a little bit tricky, it would be great to support chart in the other 2D axis.

**Comment by indapublic** [comment]
Agreed

**Comment by vuvanly** [comment]
I think for horizontal chart, this library will help you.
[http://jvloenen.home.xs4all.nl/orgchart/](http://jvloenen.home.xs4all.nl/orgchart/)

**Comment by dabeng** [comment]
Hi @unaizalakain @pjaaar @indapublic @vuvanly. Making use of option "direction" of **[OrgChart](https://github.com/dabeng/OrgChart)**(derived from jOrgChart) you could easily align the orgchart in different orientations. Please refer to demos --**[ bottom to top](http://dabeng.github.io/OrgChart/direction/bottom2top)**, **[left to right](http://dabeng.github.io/OrgChart/direction/left2right)**, **[right to left](http://dabeng.github.io/OrgChart/direction/right2left)**.

**Comment by vuvanly** [comment]
Thanks @dabeng . The new one is great.
